#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtconsole
Version  : 4.5.5
Release  : 34
URL      : https://files.pythonhosted.org/packages/05/b1/499d710ad87fd8cb7ed12f11a5e2106003580d2581c743b169181a5b7fee/qtconsole-4.5.5.tar.gz
Source0  : https://files.pythonhosted.org/packages/05/b1/499d710ad87fd8cb7ed12f11a5e2106003580d2581c743b169181a5b7fee/qtconsole-4.5.5.tar.gz
Summary  : Jupyter Qt console
Group    : Development/Tools
License  : BSD-3-Clause
Requires: qtconsole-bin = %{version}-%{release}
Requires: qtconsole-license = %{version}-%{release}
Requires: qtconsole-python = %{version}-%{release}
Requires: qtconsole-python3 = %{version}-%{release}
Requires: Pygments
Requires: ipykernel
Requires: ipython_genutils
Requires: jupyter_client
Requires: jupyter_core
Requires: traitlets
BuildRequires : Pygments
BuildRequires : buildreq-distutils3
BuildRequires : ipykernel
BuildRequires : ipython_genutils
BuildRequires : jupyter_client
BuildRequires : jupyter_core
BuildRequires : traitlets

%description
# Jupyter QtConsole
[![Build Status](https://travis-ci.org/jupyter/qtconsole.svg?branch=master)](https://travis-ci.org/jupyter/qtconsole)
[![Coverage Status](https://coveralls.io/repos/github/jupyter/qtconsole/badge.svg?branch=master)](https://coveralls.io/github/jupyter/qtconsole?branch=master)
[![Documentation Status](https://readthedocs.org/projects/qtconsole/badge/?version=stable)](https://qtconsole.readthedocs.io/en/stable/)
[![Google Group](https://img.shields.io/badge/-Google%20Group-lightgrey.svg)](https://groups.google.com/forum/#!forum/jupyter)

%package bin
Summary: bin components for the qtconsole package.
Group: Binaries
Requires: qtconsole-license = %{version}-%{release}

%description bin
bin components for the qtconsole package.


%package license
Summary: license components for the qtconsole package.
Group: Default

%description license
license components for the qtconsole package.


%package python
Summary: python components for the qtconsole package.
Group: Default
Requires: qtconsole-python3 = %{version}-%{release}

%description python
python components for the qtconsole package.


%package python3
Summary: python3 components for the qtconsole package.
Group: Default
Requires: python3-core

%description python3
python3 components for the qtconsole package.


%prep
%setup -q -n qtconsole-4.5.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1568213982
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qtconsole
cp LICENSE %{buildroot}/usr/share/package-licenses/qtconsole/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter-qtconsole

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qtconsole/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
